# Query 7: Retrieve given names of all people, and optionally the family name of their teacher

PREFIX : <http://example.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?givenName ?teacherFamilyName
WHERE {
  ?iri rdf:type foaf:Person .
  ?iri foaf:givenName ?givenName .

  OPTIONAL {
    ?iri :hasTeacher ?teacherIri .
    ?teacherIri foaf:familyName ?teacherFamilyName .
  }
}
