# 3. Retrieve the sum of the prices of novels and movies for each language label.

PREFIX : <http://example.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT ?languageLabel (SUM(?price) AS ?totalPrice)
WHERE {

    { ?work a :Novel . }
    UNION
    { ?work a :Movie . }
    
    ?work dcterms:language ?language ;
          :price ?price .
    ?language rdfs:label ?languageLabel .
}
GROUP BY ?languageLabel