# Query 2: Given name of all people with family name “Alighieri”

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?givenName
WHERE {
  ?iri rdf:type foaf:Person .
  ?iri foaf:givenName ?givenName .
  ?iri foaf:familyName "Alighieri" .
}
