# Query 10: Retrieve the texts that are not print editions (alphabetically
# ordered), starting from the third result

PREFIX : <http://example.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?label
WHERE {
    ?iri rdf:type dctypes:Text .
    ?iri rdfs:label ?label .
    MINUS
    {
        ?text :hasPrintEdition ?iri .
    }
} ORDER BY ?label OFFSET 2