# Query 7: Compute the total price of print editions written in Italian or English

PREFIX : <http://example.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT (SUM(?price) AS ?tot)
WHERE {
    ?iri :hasPrintEdition ?printEdition .
    ?printEdition :price ?price .
    {?printEdition dcterms:language wd:Q1860 . }    # English
    UNION
    {?printEdition dcterms:language wd:Q652 . }     # Italian
}